In [2]:
import numpy as np

In [2]:
dets = [[10,10,20,20,1],[15,15,15,15,1],[12,12,15,20,1],[14,12,16,20,1]]
trks = [[11,11,19,19,0],[8,9,17,16,0],[13,13,21,22,0]]

In [3]:
bb_gt = np.expand_dims(trks,0)

In [4]:
bb_gt

array([[[11, 11, 19, 19,  0],
        [ 8,  9, 17, 16,  0],
        [13, 13, 21, 22,  0]]])

In [5]:
bb_test = np.expand_dims(dets,1)

In [7]:
bb_test

array([[[10, 10, 20, 20,  1]],

       [[15, 15, 15, 15,  1]],

       [[12, 12, 15, 20,  1]],

       [[14, 12, 16, 20,  1]]])

In [9]:
xx1 = np.maximum(bb_test[..., 0], bb_gt[..., 0])

In [10]:
xx1

array([[11, 10, 13],
       [15, 15, 15],
       [12, 12, 13],
       [14, 14, 14]])

In [11]:
xx1.shape

(4, 3)

In [12]:
yy1 = np.maximum(bb_test[..., 1], bb_gt[..., 1])
xx2 = np.minimum(bb_test[..., 2], bb_gt[..., 2])
yy2 = np.minimum(bb_test[..., 3], bb_gt[..., 3])

In [13]:
yy1

array([[11, 10, 13],
       [15, 15, 15],
       [12, 12, 13],
       [12, 12, 13]])

In [14]:
xx2

array([[19, 17, 20],
       [15, 15, 15],
       [15, 15, 15],
       [16, 16, 16]])

In [15]:
yy2

array([[19, 16, 20],
       [15, 15, 15],
       [19, 16, 20],
       [19, 16, 20]])

In [17]:
w = np.maximum(0., xx2 - xx1)
h = np.maximum(0., yy2 - yy1)

In [18]:
w

array([[8., 7., 7.],
       [0., 0., 0.],
       [3., 3., 2.],
       [2., 2., 2.]])

In [19]:
h

array([[8., 6., 7.],
       [0., 0., 0.],
       [7., 4., 7.],
       [7., 4., 7.]])

In [20]:
wh = w*h

In [21]:
wh

array([[64., 42., 49.],
       [ 0.,  0.,  0.],
       [21., 12., 14.],
       [14.,  8., 14.]])

In [22]:
o = wh/((bb_test[...,2] - bb_test[..., 0]) *
              (bb_test[..., 3] - bb_test[..., 1]) +
              (bb_gt[..., 2] - bb_gt[..., 0]) *
              (bb_gt[..., 3] - bb_gt[..., 1]) - wh)

In [23]:
o

array([[0.64      , 0.34710744, 0.39837398],
       [0.        , 0.        , 0.        ],
       [0.31343284, 0.16      , 0.17073171],
       [0.21212121, 0.11267606, 0.18918919]])

In [3]:
colors = np.random.randint(0, 256, (32, 3))

In [4]:
colors

array([[240, 122,  30],
       [153, 138,   8],
       [ 27,  80, 110],
       [ 47,  33, 198],
       [237, 232, 246],
       [  9, 245, 192],
       [236,  30,  88],
       [181, 153,  38],
       [199, 184, 128],
       [217,  75,  67],
       [ 54, 154, 182],
       [158, 111, 157],
       [ 13, 222,  28],
       [ 26, 145, 149],
       [ 35,  87, 216],
       [ 21,  29, 142],
       [ 78, 143, 232],
       [161,  79,  22],
       [178,  54,  36],
       [194,  48, 123],
       [222,  29,   7],
       [109,  96, 206],
       [143,  19,  20],
       [ 78, 166, 180],
       [ 82, 152, 230],
       [113, 220,  98],
       [ 26, 244, 143],
       [234,  16,  82],
       [235,  17,   0],
       [129,  66,  99],
       [225,  75, 182],
       [128,  65, 117]])