In [ ]:
%matplotlib inline


什么是PyTorch?
================

PyTorch是一个基于python的科学计算包，主要针对两类人群：

-   作为NumPy的替代品，可以利用GPU的性能进行计算
-   作为一个高灵活性、速度快的深度学习平台

入门
---------------

### 张量

Tensor(张量）类似于NumPy的ndarray，但还可以在GPU上使用来加速计算。



In [2]:
from __future__ import print_function
import torch

<div class="alert alert-info"><h4>Note</h4><p>An uninitialized matrix is declared,
    but does not contain definite known
    values before it is used. When an
    uninitialized matrix is created,
    whatever values were in the allocated
    memory at the time will appear as the initial values.</p></div>



Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[5.9694e-39, 1.0010e-38, 1.0102e-38],
        [1.0561e-38, 1.0469e-38, 1.0653e-38],
        [1.0469e-38, 4.2246e-39, 1.0286e-38],
        [1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39]])


Construct a randomly initialized matrix:



In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6555, 0.2010, 0.5330],
        [0.8561, 0.0390, 0.9488],
        [0.0261, 0.4982, 0.7917],
        [0.9416, 0.2289, 0.9771],
        [0.2752, 0.0869, 0.8989]])


Construct a matrix filled zeros and of dtype long:



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.5288, -0.9197, -0.9625],
        [-0.6804,  2.0704, -1.5042],
        [ 1.8517,  1.0034, -0.5436],
        [ 0.7162, -0.2793,  1.8727],
        [ 1.1850, -0.9715,  0.2732]])


Get its size:



In [8]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.5263, -0.1728, -0.0699],
        [-0.1353,  2.1054, -0.5720],
        [ 2.3765,  1.0567, -0.2747],
        [ 0.8106,  0.2011,  2.3375],
        [ 1.5897, -0.5988,  0.8384]])


Addition: syntax 2



In [10]:
print(torch.add(x, y))

tensor([[ 1.5263, -0.1728, -0.0699],
        [-0.1353,  2.1054, -0.5720],
        [ 2.3765,  1.0567, -0.2747],
        [ 0.8106,  0.2011,  2.3375],
        [ 1.5897, -0.5988,  0.8384]])


Addition: providing an output tensor as argument



In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.5263, -0.1728, -0.0699],
        [-0.1353,  2.1054, -0.5720],
        [ 2.3765,  1.0567, -0.2747],
        [ 0.8106,  0.2011,  2.3375],
        [ 1.5897, -0.5988,  0.8384]])


Addition: in-place



In [12]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.5263, -0.1728, -0.0699],
        [-0.1353,  2.1054, -0.5720],
        [ 2.3765,  1.0567, -0.2747],
        [ 0.8106,  0.2011,  2.3375],
        [ 1.5897, -0.5988,  0.8384]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [13]:
print(x[:, 1])

tensor([-0.9197,  2.0704,  1.0034, -0.2793, -0.9715])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.5743])
-0.5742892026901245


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [20]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!